name: Publish to GitHub Packages
on:
  push:
    branches:
      - master
  release:
    types: [ created ]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: java setup
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: gradle setup
        uses: gradle/gradle-build-action@v2

      - name: publish
        run: ./gradlew publishSgf4kPublicationToGitHubPackagesRepository
