name: Unit tests
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: java setup
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: gradle setup
        uses: gradle/gradle-build-action@v2

      - name: test
        run: ./gradlew :test --tests "com.judas.sgf4k.*"
